#!/bin/bash
echo "Enter Numbers"
read n
sum=0
for ((i=1; i<=n; i++))
do
        sum=$((sum + i))
done
echo "$sum"


//OR

#!/bin/bash
echo "Enter Numbers"
read n

numbers=$(seq -s+ 1 $n)
sum=$(($n * ($n + 1) / 2))  
echo "$numbers=$sum"
