#!/bin/bash

echo "Enter a 5-digit number:"
read num

rev=0
while [ "$num" -gt 0 ];
do
    digit=$((num % 10))
    rev=$((rev * 10 + digit))
    num=$((num / 10))
done

echo "Reversed Number: $rev"

------------------------------
Output:
------------------------------
Enter a 5-digit number:
123456
Reversed Number: 654321
